##############################[ Freecam ]###########################
##                                                                ##
##                   Encontrou algum bug? Reporte!                ##
##                     Discord: itzxitadoo                        ##
##               Github: https://github.com/ItzXitado/            ##
##                                                                ##
####################################################################

#O limite de distância funciona por permissão, se o jogador tiver por exemplo a perm freecam.100 o limite é 100, basta usar freecam. e o limite que quiser :D